Prefer Setuptools-SCM to Poetry (for Now) (#26)
* Prefer Setuptools-SCM to Poetry (for Now)

Users often see this warning:

```
/parameter_expansion/init.py:40: UserWarning: Unable to determine version for parameter_expansion. Falling back to 0.0.0+unknown
```

This warning indicates that users are getting packages that do not have
proper package metadata, including the version. I believe this is caused
by problems building and shipping the package using
poetry-dynamic-versioning.

I insist on being able to automatically maintain versions in lock-step
with git tags. So, I'm returning to setuptools for packaging, using
setuptools-scm to meet my requirement.

I also moved the source code into src/ and the isolated the tests in
tests/. Users who install the wheel will only get the essential runtime
code. Pip will prefer the wheel by default. Users who install the sdist
will still get the tests.

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -32,19 +32,17 @@ jobs:
       with:
         python-version: '3.9'
 
-    - run: pip install poetry poetry-dynamic-versioning
-
     - name: Install Package
-      run: poetry install
+      run: python -m pip install build
 
     - name: Bump Version
       run: |
         desc=$(git describe)
         head=$(git show-ref --hash --head HEAD)
-        version=$(poetry version --short)
+        version=$(python -m setup --version)
         case "$version" in
           0.0.0*)
-            echo 'Poetry failed to get version' >&2
+            echo 'Failed to get version' >&2
             false
             ;;
           "$desc")
@@ -52,13 +50,24 @@ jobs:
             false
             ;;
         esac
-        IFS=. read -r major minor bugfix _ <<< "$version"
-        bump="$major.$minor.$(( 1 + bugfix ))"
+        IFS=. read -r major minor patch _ <<< "$version"
+        bump="$major.$minor.$patch"  # setuptools-scm increments the patch
         set -x
         gh release create --target "$head" "$bump"
         git fetch --tags origin
         git tag -fm "$bump" "$bump"  # retag with annotated tag
         git push --tags --force origin "$bump"
-        poetry version --short | grep -qF "$bump"
-        poetry build
+        python -m build .
+        find dist
+        # test the package versions are fixed outside of git
+        sdist_version=$(tar -O -xf "dist/parameter-expansion-$bump.tar.gz" "parameter-expansion-$bump/src/parameter_expansion.egg-info/PKG-INFO" | awk '/^Version:/{print $2}')
+        wheel_version=$(unzip -p "dist/parameter_expansion-$bump.whl" "parameter_expansion-${bump}.dist-info/METADATA" | awk '/^Version:/{print $2}')
+        if [[ $bump != $sdist_version ]]; then
+          echo "Expected new version $bump, but sdist has version $sdist_version." >&2
+          false
+        fi
+        if [[ $bump != $wheel_version ]]; then
+          echo "Expected new version $bump, but wheel has version $wheel_version." >&2
+          false
+        fi
         gh release upload "$bump" dist/*
